### ISSUE TITLE
Accidental logout too easy

### ISSUE THREAD

**Issue by Skittles4R32** [smelliott100/SarTechTools#12]
The bottom-most symbol on the right hand side seems to log me out of my account(i assume this is what is happening)without any warning or communication that it is doing so, the extra features simply dissapear that i had access to when logged in. Anyone just clicking through the app trying to figure out what all the symbols mean would unknowingly log themselves out by clicking there. Perhaps logging out could be made more clear that by clicking there it would log you out? Or perhaps be incorporated into the same icon as the login?

**Comment by elliottshane** [comment]
Add "Are you sure?" before logout

**Comment by Skittles4R32** [comment]
Or even "Do you want to logout?" So it's clear what that action will do
