### ISSUE TITLE
Android "My Location"

### ISSUE THREAD

**Issue by xopenex** [smelliott100/SarTechTools#13]
Hi. Using Samsung Galaxy S10+ with Android Version 10.

1. These 3 words seem to change sometimes while stationary.
2. Share my location brings an error message "invalid recipient" and once clearing the error message ends up on my "Messages" "Conversations" list page.
3. Does not load my location on google maps after opening Google maps. I always end up freezing in Antarctica! Not a good place for me, I havent had any cold weather training yet!

**Comment by elliottshane** [comment]
Thanks,

- W3W works for ? other are reporting it does not. 
- Share my location was developed for IOS, I need to make it work for android, will put that on the list.

**Comment by elliottshane** [comment]
Should have been fixed in latest version
