### ISSUE TITLE
What3Words Field too small

### ISSUE THREAD

**Issue by elliottshane** [smelliott100/SarTechTools#6]
some what 3 words overrun the screen on location.

**Comment by Skittles4R32** [comment]
What 3 words field does not populate with any values in coordinate calculator

**Comment by elliottshane** [comment]
should not in coordinate calculator, that is where you put one in to convert.  I can add your current location coordinate if you think that would be better.

**Comment by Skittles4R32** [comment]
That would be awesome! When you put in a UTM, would it be possible for the
corresponding What3word coordinate to appear in the lower screen along with
the other lat/lon conversions?

**Comment by elliottshane** [comment]
Corrected
